---
title: "On # of days of bad mental health in the past 30 days"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(survey)
library(srvyr)
library(readr)
library(forcats)
library(gtsummary)
```

```{r include = FALSE}
brfss21_data = read_csv("./data/cleaned_brfss21.csv") %>%
  mutate(mh_cat3 = factor(mh_cat3, levels = c("none", "<=15 days", ">15 days")),
         mh_bin = factor(mh_bin, levels = c("<=15 days", ">15 days")),
         depression = factor(depression, levels = c("no", "yes")),
         sex = factor(sex, levels = c("male", "female")),
         children = factor(children, levels = c("none", "one or two", "three or more")),
         state = factor(state),
         race = factor(race, levels = c("white", "black", "asian", "hispanic", "other")),
         education = factor(education, levels = c("less than high school", "high school or some college", "bachelors or higher")),
         income = factor(income, levels = c("<=35000", "35000-75000", ">75000")),
         employment = factor(employment, levels = c("employed", "homemaker/student/retired", "unemployed")),
         age = factor(age, levels = c("18-29", "30-49", "50-64", "65+")),
         general_health = factor(general_health, levels = c("excellent", "very good/good", "fair/poor")),
         exercise = factor(exercise, levels = c("yes", "no")))
```

```{r include = FALSE}
# Set options for allowing a single observation per stratum 
options(survey.lonely.psu = "adjust")

# Create survey design 
brfss_design = as_survey_design(brfss21_data, id = 1, strata = ststr, weight = llcpwt)
```

### Summary statistics

Below is the unweighted counts of the all included demographic variables, exposure, and other covariates, grouped by the self-reported number of days with bad mental health in the past 30 days in the following three categories: none, between 1 and 15 days, and more than 15 days. 

```{r}
tb1_unweighted =
  brfss_design$variables %>%
  tbl_summary(by = mh_cat3, percent = "row", 
              include = c(sex, race, age, marital_status,
                             children,
                             education, income, employment,
                             general_health, exercise),
              type = list(exercise ~ "categorical"))

tb1_unweighted
```


```{r weighted summary}
tb1_weighted =
  brfss_design %>%
  tbl_svysummary(by = mh_cat3, percent = "row", 
                 include = c(sex, race, age, marital_status,
                             children,
                             education, income, employment,
                             general_health, exercise),
                  type = list(exercise ~ "categorical"))

tb1_weighted
```



