---
title: "BRFSS Import"
author: "Ziqing Wang"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rio)
library(haven)
library(readr)
```

Import the raw XPT data file into RStudio. 
```{r}
BRFSS2021 = read_xpt(
  './data/LLCP2021.XPT',
  col_select = NULL,
  skip = 0,
  n_max = Inf,
  .name_repair = "unique"
) %>% janitor::clean_names()
```

Preview the data. 
```{r}
head(BRFSS2021)
```

Reduce the data set size by selecting only variables of interest and variables necessary for data analysis (e.g., weight variables). 
```{r}
tidy_brfss21 = BRFSS2021 %>%
  select(psu, llcpwt, ststr, # survey weight variables
         menthlth, addepev3, # mental health outcomes
         sex, chldcnt, # exposures
         state, race, educa, income3, employ1, marital, ageg5yr, # demographic covariates
         exerany2, genhlth) %>% # health-related covariates
  mutate(mh_cat3 = case_when(menthlth == 88 ~ "none",
                             menthlth %in% seq(1, 15) ~ "<=15 days",
                             menthlth %in% seq(16, 30) ~ ">15 days"),
         mh_bin = case_when(menthlth %in% c(seq(1,15), 88)  ~ "<=15 days",
                            menthlth %in% seq(16, 30) ~ ">15 days"),
         depression = case_when(addepev3 == 1 ~ "yes",
                                addepev3 == 2 ~ "no"),
         sex = case_when(sex == 1 ~ "male",
                         sex == 2 ~ "female"),
         children = case_when(chldcnt == 1 ~ "none",
                              chldcnt %in% c(2, 3) ~ "one or two",
                              chldcnt %in% c(4, 5, 6) ~ "three or more"),
         race = case_when(race == 1 ~ "white",
                          race == 2 ~ "black",
                          race == 4 ~ "asian",
                          race == 8 ~ "hispanic",
                          race %in% c(3,5,6,7) ~ "other"),
         education = case_when(educa %in% c(1,2,3) ~ "less than high school",
                               educa %in% c(4,5) ~ "high school or some college",
                               educa == 6 ~ "bachelors or higher"),
         income = case_when(income3 %in% seq(1,5) ~ "<=35000",
                            income3 %in% c(6,7) ~ "35000-75000",
                            income3 %in% c(8,9,10) ~ ">75000"),
         employment = case_when(employ1 %in% c(1,2) ~ "employed",
                                employ1 %in% c(5,6,7) ~ "homemaker/student/retired",
                                employ1 %in% c(3,4,8) ~ "unemployed"),
         marital_status = case_when(marital == 1 ~ "married",
                                    marital %in% seq(2,6) ~ "not married"),
         age = case_when(ageg5yr %in% c(1,2) ~ "18-29",
                         ageg5yr %in% c(3,4,5,6) ~ "30-49",
                         ageg5yr %in% c(7,8,9) ~ "50-64",
                         ageg5yr %in% c(10,11,12,13) ~ "65+"),
         general_health = case_when(genhlth == 1 ~ "excellent",
                                    genhlth %in% c(2,3) ~ "very good/good",
                                    genhlth %in% c(4,5) ~ "fair/poor"),
         exercise = case_when(exerany2 == 1 ~ "yes",
                              exerany2 == 2 ~ "no"),
         mh_cat3 = factor(mh_cat3, levels = c("none", "<=15 days", ">15 days")),
         mh_bin = factor(mh_bin, levels = c("<=15 days", ">15 days")),
         depression = factor(depression, levels = c("no", "yes")),
         sex = factor(sex, levels = c("male", "female")),
         children = factor(children, levels = c("none", "one or two", "three or more")),
         state = factor(state),
         race = factor(race, levels = c("white", "black", "asian", "hispanic", "other")),
         education = factor(education, levels = c("less than high school", "high school or some college", "bachelors or higher")),
         income = factor(income, levels = c("<=35000", "35000-75000", ">75000")),
         employment = factor(employment, levels = c("employed", "homemaker/student/retired", "unemployed")),
         age = factor(age, levels = c("18-29", "30-49", "50-64", "65+")),
         general_health = factor(general_health, levels = c("excellent", "very good/good", "fair/poor")),
         exercise = factor(exercise, levels = c("yes", "no"))
  ) %>%
  filter(!state %in% c(2, 66, 72, 78)) %>% # keep only contiguous US states
  filter(!is.na(depression), !is.na(mh_cat3)) # remove observations with missing outcome variables

```

Export the csv with reduced number of variables and observations.
```{r}
write_csv(tidy_brfss21, "./data/cleaned_brfss21.csv")
```

