---
title: "children_data"
output: html_document
date: "2022-11-29"
---
---
title: "children_dep"
output: html_document
date: "2022-11-26"
---
```{r}
library(tidyverse)
```


```{r}
child_data = 
  read_csv("./data/cleaned_brfss21.csv") %>% 
  select(children, chldcnt, depression, menthlth, mh_cat3, mh_bin) %>% 
  drop_na() %>% 
   mutate(
      children01 = 
        case_when(
          children %in% c("none") ~ "No",
          TRUE ~ "Yes"))

child_data['menthlth'][child_data['menthlth'] == 88] <- 0
```

## Depression: Yes or No?

### Children: Yes or No? 

barplot

```{r}
child1 = 
  child_data%>% 
    group_by(children01) %>% 
    summarise(
      n = n(),
      n_dep = sum(depression == "yes"),
      prv = n_dep/n
    ) 

child1%>% 
  ggplot(aes(children01, prv)) +
  geom_col() +
  geom_text(aes(label=prv), vjust=-.5, size=3.5)
```

proption test

```{r}
dep_prp_test = prop.test(c(58799, 22239), n = c(304974, 106791), correct = F)

dep_prp_test

```


### Children: How many?

barplot

```{r}
child2 = 
  child_data %>% 
  group_by(chldcnt) %>% 
  summarize(
    n = n(),
    n_dep = sum(depression == "yes"),
    prv2 = n_dep/n
  )

child2 %>% 
  ggplot(aes(chldcnt, prv2)) +
  geom_col()
```

chi-square test

```{r}
child2 %>% 
  mutate(
    n_non_dep = n - n_dep,
    chldcnt = as.factor(chldcnt),
    n_dep = as.numeric(n_dep),
    n_non_dep = as.numeric(n_non_dep)) %>% 
  select(chldcnt, n_dep, n_non_dep)

chisq.test(child2)
```


## Depression: How many days?

```{r}
child3 = 
  child_data %>% 
    ggplot(aes(children01, menthlth)) +
    geom_boxplot()

child3
```

```{r}
child_data %>% 
  mutate(chldcnt = as.factor(chldcnt)) %>% 
  ggplot(aes(chldcnt, menthlth)) +
    geom_boxplot()
```

