---
title: "Proposal"
output: github_document
---

### Group members
Yichen Lyu (yl5220), Ziqing Wang (zw2899), Zhaoqianyu Xiong (zx2424), Zirui Zhang (zz3039)

### Tentative project title
US State-level gender differences in mental health and their associated factors
 
### Motivation
The main goals of this project are to 1) compare age-adjusted state-level differences in depression prevalence and average number of days with unwell mental health between US adult men and women and 2) examine factors that potentially affect mental health outcomes. 
 
### Intended final products
Current literature provide inconsistent evidence on gender difference in mental health outcomes. According to WHO, “women are more likely to be treated for depression than men even though the rates of depression don’t differ greatly between the gender”. However, there are also research studies suggesting that women are more likely than men to have depression. It’s thus important to find out whether there indeed is a gender gap in mental health outcomes, which may in turn supply evidence that help answer other public health questions, such as whether women are overtreated for mental health disorders. Therefore, for our project, we expect the results to show whether there is an inequality between men and women in mental health outcomes such as depression. Additionally, we are also interested in state-level gender differences and factors associated with mental health outcomes. Ultimately, we hope to use these information to construct a comprehensive picture of gender and mental health among US adults.
 
### Anticipated data sources
The dataset we use is “The 2021 BRFSS data”, which was downloaded from https://www.cdc.gov/brfss/annual_data/annual_2021.html.
 
### Planned analyses / visualizations / coding challenges        
The outcome variables are whether the person has been diagnosed as having depression and the number of days of having negative mental health last month. Both are self-reported.  

The exposure variable is gender (male, female). For now, we intend to calculate the difference of depression prevalence and the difference of the number of days of having negative mental health between men and women for each state.  

Since we are examining factors that contribute to gender inequality in mental health outcomes, we plan to do some regression analysis to determine what specific factors affect mental health in men and women. We intend to identify relevant covariates by conducting literature review and a series of univariate analyses. Plots such as scatterplot, histogram, heatmaps can be drawn to show the results visually.  

Since the size of the dataset is a bit large, it can post a challenge for us to push it to Github. Also, there are over 300 variables in the dataset. It will be challenging to select a set of covariates to adjust in regression analyses.
 
### Planned timeline:                                                                                                    	
11/12: Form a team and finish proposal  
11/15-18: Project review meeting    
12/10: submit report with detailed description of our project, finish our webpage creation giving overview of our project with a short explanatory video, and do peer assessment  
 
### Reference
Leibenluft, E. (Ed.). (1999). Gender differences in mood and anxiety disorders: From bench to bedside.  

Partner, Q. (2019, September 16). Exploring gender bias in healthcare. Fierce Healthcare. Retrieved November 10, 2022, from https://www.fiercehealthcare.com/sponsored/exploring-gender-bias-healthcare#:~:text=The%20Dangers%20of%20Gender%20Bias,expect%20patient%20outcomes%20to%20suffer  

Centers for Disease Control and Prevention (CDC). Behavioral Risk Factor Surveillance System Survey Data. Atlanta, Georgia: U.S. Department of Health and Human Services, Centers for Disease Control and Prevention, 2022.
 
 
 
