---
title: "Report"
output: 
 html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Introduction
Current literature provide inconsistent evidence on gender difference in mental health outcomes. According to WHO, “women are more likely to be treated for depression than men even though the rates of depression don’t differ greatly between the gender”. However, there are also research studies suggesting that women are more likely than men to have depression. To solve this confusion, the main goals of this project are to 1) compare state-level differences in depression prevalence and average number of days with unwell mental health between US adult men and women and 2) examine factors that potentially affect mental health outcomes. After finding out whether there indeed is a gender gap in mental health outcomes, it may in turn supply evidence that help answer other public health questions, such as whether women are overtreated for mental health disorders. 

## Background and related work
As Leibenluft, E mentioned in his book *Gender differences in mood and anxiety disorders: From bench to bedside.*, whether the presentation and course of illness differ by gender remain unknown because of different researches give different results. And based on the large amount of data given by CDC (*Behavioral Risk Factor Surveillance System Survey Data*), we believe we can answer this question by means of data analysis. At the same time, ignoring these differences (as it always has been) may cause danger to patients, stated by Partner, Q in *Exploring gender bias in healthcare*. For men, they are less likely to be treated partially because they resist discussing their emotion with doctor due to gender stereotype. For women, we also need to guarantee that they won't be overtreated. These related works show the importance of finding out the main effects for depression of different genders. Also, noticing that the United States is a country with great diversity among different states, we decided to explore the circumstances at state-level.  

Additionally, we are interested in how presence of children in the household might affect women and men's mental health differently. This question was inspired by personal observations and experience - Women are usually more likely to assume more care-giving responsibilities in the household. Then is women's mental health affected more than men's by the presence of children in the household? 

## Research questions
### Main research questions
We are interested in the following questions:

* How does the geological distribution of mental health outcomes across US states differ among men and women?

* Do men and women have different mental health outcomes, taking into account of demographic, socioeconomic, and health factors?

* Does the number of children in the household affect the mental health of men and women differently?

### Post-hoc questions
While answering our main research questions, some additional interesting questions emerged, and we tried answering some of them after our main analyses. These "post-hoc" questions include the following:  

* Is state-level prevalence of mental health outcomes associated with state-level gender inequality?  
* How do mental health care service utilization and opinions on mental health disorders differ among men and women? How are these differences associated with women and men's mental health?

## Method

### Data
We uses multiple data sources for our project. For our main research questions, we used the 2021 Behavioral Risk Factor Surveillance System (BRFSS) data downloaded from [the CDC website](https://www.cdc.gov/brfss/annual_data/annual_2021.html). BRFSS is an annual, nationally representative cross-sectional survey on non-institutionalized American adults' health-related risk behaviors, health conditions, and health care seeking behaviors. The BRFSS is a complex survey that involves multistage clustering and stratification. In 2021, 438,693 Americans were included in the BRFSS.  

For our post-hoc explorations, we used the Women, Peace, and Security (WPI) index published by Georgetown University. According to the [organization's website](https://giwps.georgetown.edu/the-index/), the WPS index draws from recognized data source to quantify women’s inclusion, justice, and security. We used this index as a measurement of state-level gender inequality. We also downloaded the US states' GDP per capita in 2021 from [here](https://www.statista.com/statistics/248063/per-capita-us-real-gross-domestic-product-gdp-by-state/). We also used the 2012 BRFSS data, which is the last (most recent) BRFSS survey that contains questions on mental health service utilization and questions related to attitudes and beliefs toward mental health care and stigmatization. This data set was also downloaded from [the CDC website](https://www.cdc.gov/brfss/annual_data/annual_2012.html). 

### Outcome variables
We used two variables to measure mental health. The first variable is the self-reportd past depression. The participants were asked if they have ever been told that they had a depressive disorder (including depression, major depression, dysthymia, or minor depression). The second variable is the self-reported number of days of bad mental health in the past 30 days. The participants were asked: "Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?".  

For the first outcome variable, we dichotomized it into a binary variable with two levels: "yes" and "no". For the second outcome variable, we recoded it into a binary variable with two levels: $\leq$ 15 days mental health not good in the past 30 days, and more than 15 days mental health not good in the past 30 days.  

We used the first outcome variable as a proxy to measure respondents' chronic mental health status, since it asks for any occurrence of depression, a common mental health disorder, across the respondent's life span. We used the second outcome variable as a proxy for measuring respondents' temporal mental health status, since it asks about recent mental health status.   

### Exposures
We are interested in two exposure variables. The first one is respondent's gender coded as female or male based on their answers to whether they were male or female and whether they were male or female at birth. The second exposure variable is the number of children in the respondent's household, which was recoded to three levels: none, one or two, and three or more.

### Covariates
Demographic covariates in our analyses include race/ethnicity (recoded as non-Hispanic white, black, Asian, Hispanic, and other), age (recoded as 18-29 years old, 30-49 years old, 50-64 years old, and 65 or older), employment status (recoded as employed for salary, homemake/student/retired, and unemployed), and marital status (recoded as married and not married). Socioeconomic cavariates include education level (recoded as less than high school, high school or some college, and Bachelors's degree or higher) and annual income (recoded as $\leq$ 35000 dollars, between 35000 and 75000 dollars, and more than 75000 dollars). Health-related covariates include self-reported general health (recoded as excellent, very good/good, and fair/poor) and any self-reported exercises in the past 30 days (recoded as yes and no).

### Statistical Analysis
National surveys such and BRFSS and NHIS are not simple random samples because observations have different probabilities of being sampled due to complex survey designs. Therefore, before analyzing nationally representative survey data, we must apply survey weights, or all our estimates will be invalid. In our project, after selecting, cleaning, and recoding the variables, we converted the data set into a survey design object using the srvyr package. 

We computed weighted and unweighted summary counts of exposure and covariate categories in each level of the two mental health outcome variables. We used Chi-squared tests for weighted survey data to identify differences in mental health outcomes by gender as well as differences in mental health outcomes and other variables (e.g., number of children in household, age, race/ethnicity) by gender.  

We used binary logistic regression to examine the association between gender and past depression and >15 days mental health not good in the past 30 days, respectively. We started with a crude model that only included the exposures (gender and the number of children in the household). Then we constructed a larger model by adding demographic covariates, which are age, race/ethnicity, and marital status. Then we constructed another model by adding socioeconomic covariates to the previous model, which are education, annual income, and employment status. Finally, we constructed our full model by adding physical health related variables, which are self-reported general health and self-reported any physical exercise in the past 30 days. Survey weights were applied to all regression models as well. The regression models were compared using the AIC criterion. Models with the lowest AIC values were selected as final models.  

The final model for each of the two mental health outcomes were used to compute the predictive marginal means for each independent variable. According to the documentation of the survey package, the predictive marginal mean for one level of a factor variable is the probability-weighted average of the fitted values for the model on new data where all observations are set to that specific level of the factor variable but have whatever values of adjustment covariates they really have. In our case where we have a binary logistic regression model, the predictive marginal mean shows the effect of a categorical variable on the predicted probability of the response variable, adjusting for all other predictor variables included in the model. We computed the predictive marginal means because we think it better demonstrates the magnitude of a factor predictor's effect on the outcome variable than the odds, because odds are less intuitive than probabilities. The final models were also used to calculate the predicted probability of each mental health outcome given each combination of levels of independent variables. We put these results in a Shiny app so that users can play around with different factor levels and observe how they affect mental health outcomes according to our selected model.  

To check whether the number of children in the household has differential effect on mental health by gender, we subsetted the data by gender (one data set only has men, the other only has women) and ran the best logistic regression models selected from above separately on the two subsetted data sets, excluding the gender variable. 


## Results

### Explanatory Analysis
In our exploratory analysis for the outcome variable, the self-reported number of days of bad mental health in the past 30 days, we first examined whether it is associated with the exposure, respondent's gender using a chi-square test. The resulting p-value of 1.014e-67 indicates that the number of days of bad mental health in the past 30 days is dependent on gender, which allows us to proceed to study the relationship between the number of days of bad mental health in the past 30 days and other covariates, on top of the effects of gender. By creating a barplot, we first studied how the number of children in the household affected the self-reported prevalence of over 15 days of bad mental health in the past 30 days among men and women. Based on the plot, we found an interesting result that men who have children in the household have a significantly lower prevalence of self-reported over 15 days of bad mental health while women who have children don't, which was verified by a chi-square test showing the p-value for men and women to be 0.023 and 0.093. That is, the number of children in the household is significantly associated with self-reported over 15 days of bad mental health in the past 30 days among men but not women. Next, we created a barplot to examine how gender and race together associate with the self-reported prevalence of over 15 days of bad mental health in the past 30 days. The result is that the prevalence of reported more than 15 days of in the past 30 days being in bad mental health is higher in women than men for all ethnicities, which includes White, Black, Asian, Hispanic, and others. More specifically, White women have the highest prevalence of bad mental health among Black, Asian, and Hispanic women, and the same holds true for Black Men. Another covariate, age, was also studied with gender together for the effects on the prevalence of more than 15 days of being in bad mental health. Through the barplot generated, we found that for women, the prevalence of self-reported over 15 days of bad mental in the past 30 days drops slightly when entering the age group of 50-64, but decreases noticeably when entering the age group of 30-49 and of 65+ (the same trend is displayed among men but in smaller magnitude). This result was supported by the confidence interval plot below (the gap in the magnitude of change in prevalence of a self-reported number of days in bad mental health in the past 30 days might be an indication of aging affecting self-reported bad mental health days differently for men and women). 

We then took a closer look at the outcome variable of self-reported past depression. Similarly, 
for starters, we examined if it is associated with gender by the chi-square test. The small p-value (0) indicates that the prevalence of self-reported past depressions is dependent on gender. Then, we tested the effects of the number of children in households on past depression based on gender through a barplot. An interesting observation is that similar to the self-reported number of days of bad mental health in the past 30 days, the prevalence of depression is also significantly lower in men who have children in the family than in women who have children. The p-value of 0.663 and 3.49e-12 from the chi-square test demonstrate that self-reported past depression is indeed significantly associated with the number of children in the household among men instead of women. Besides, the result discussed above is also proved by the confidence interval for depression among men with different number of children in the household, with the confidence interval of the respondents having no children has no overlap with that of the respondents having one or two children and respondents having three or more children. Then, the association of gender and race together with self-reported depression was studied. From the barplot, it can be observed that the prevalence of past depression is higher in women than men for all races included in the dataset, with White females and White males having the highest prevalence of depression among White, Black, Asian, and Hispanic people in specific. The association of age and gender with depression was also examined through a chi-square test and barplot, and the result is that for women, the prevalence of self-reported past depression remains stable between the age group 30-49 and 50-64, but decreases significantly for the age group 65+. A confidence intervals plot was drawn for illustration, and the gap in the magnitude of changes in the prevalence of self-reported depression shows that age might affect depression differently among men and women. 

By examining how gender, race, age, and the number of children in households affect the self-reported number of days of bad mental health in the past 30 days and self-reported past depression, we found that all the factors, to some extent, influence the self-reported number of days of bad mental health in a similar way to depression. Accordingly, we presume that this is because longer periods of bad mental health can lead to depression. Correspondingly, people with depression are much more likely to be in bad mental health for a longer period. 

In addition to examining how gender, the number of children in households, race, and age are associated with the two outcome variables discussed above, we also studied the state-level distribution of the two variables. We first looked at the top 10 states with the highest and lowest estimated percentage of women and men who self-reported past depression through bar plots. The plot below shows that West Virginia has the highest estimated percentage of women who self-reported past depression, followed by Kentucky, Utah, Tennessee, Indiana, Oregon, Oklahoma, Louisiana, Vermont, and Arkansas. In detail, the estimated percentage of self-reported depression among women is around 30% in all these states, with very small differences in magnitude. Then, visualizing the ten states with the lowest estimated percentages of self-reported depression among women, we found that Hawaii has the lowest estimates, followed by California, New York, New Jersey, Delaware, Illinois, Maryland, Nevada, Georgia, and Connecticut. Bar plots for the ten states with the highest and lowest estimated percentages of self-reported depression among men were drawn as well. The results are that Vermont has the highest estimated percent of self-reported depression, followed by West Virginia, Arkansas, Tennessee, Kentucky, Rhode Island, Louisiana, Oregon, Oklahoma, and Washington, DC. In specific, the estimated percentage of self-reported depression among men is around 20% in all these states, with very small differences in magnitude. Additionally, compared with data for women, all these states also have the highest estimated percent of self-reported depression among women, except for Rhodes Island and Washinton, DC, which might indicate a high disparity in mental health outcomes in the remaining eight states. Regarding the states with the lowest estimated percent of depression among men, Hawaii has the lowest percent value, followed by South Dakota, Maryland, Delaware, Iowa, Illinois, California, Nevada, Arizona, and Wisconsin. Again, the difference in magnitude is small. Among these states, South Dakota, Iowa, Nevada, Arizona, and Wisconsin were not among the top 10 states that have the lowest estimated % of self-reported past depression among women. This observation reiterates the possibility of a larger gender gap in this mental health outcome in certain states. A grouped barplot was then created for a generalized visualization of the data presented above. The result shows that the prevalence among women is the highest in West Virginia and lowest in Hawaii. Interestingly, this prevalence among men did not show a decrease as obvious as that among women, indicating that the gender difference in this outcome is larger in some states than others. As a further investigation, another grouped barplot of the prevalence of self-reported past diagnosis of depression by gender in each US state was created, arranged in descending order by the difference of the value of this estimate between men and women. The graph shows that the ten states that have the largest difference in the estimated % of self-reported past depression are, in order, Kentucky, Indiana, Wisconsin, Utah, West Virginia, Montana, Oregon, North Dakota, Oklahoma, and Tennessee. Among these ten states, Kentucky, Indiana, Utah, West Virginia, Oregan, Oklahoma, and Tennessee are also in the top 10 states that have the highest estimated % of self-reported past depression among women, suggesting these states not only have overall high past depression prevalence but also high gender disparity in past depression prevalence. 

The same analysis procedures were repeated for the outcome variable, the percent of respondents who self-reported more than 15 days of mental health not good in the past 30 days. We can see that the top 10 states with the highest estimated percentage of women who self-reported more than 15 days of bad mental health in the past 30 days are in order, West Virginia, Alabama, Oklahoma, Kentucky, Arkansas, Tennessee, Louisiana, Utah, Nevada, and Ohio. According to the graph, the estimated percentages of self-reported >15 days where mental health is not good among women are around 15% in all these states, with small differences in magnitude. Next, based on the plot showing the ten states with the lowest estimated percentage of women who self-reported >15 days where mental health was not good in the past 30 days, we found that the top 10 states with the lowest estimated percentage of women self-reported > 15 days mental health not good in the past 30 days are in order, Hawaii, South Dakota, Washington DC, Minnesota, Alaska, New York, North Dakota, Nebraska, New Jersey, and Maryland. The differences in the magnitude of this mental health outcome are small among these states. The visualization for the ten states with the highest estimated percent of self-reported >15 days mental health not good in the past 30 days among men shows that Arkansas has the highest estimated percent, with Tennessee, West Virginia, Nevada, Kentucky, South Carolina, Alabama, Vermont, Oklahoma, and Louisianna followed. Specifically, the estimated percents of self-reported >15 days mental health not good in the past 30 days among men are around 10% in all these states, which is close in value to the ten lowest percents of this mental health outcome among women, as we saw above. It is also worth noting that these states overlap with the top 10 states where the most percent of women reporting >15 days of mental health not good in the past 30 days, except for Rhodes Island and Washington DC. This indicates that the eight overlapping states probably have the highest percentage of people reporting more than half of the past 30 days mental health not good. The generalized grouped barplot by gender of female shows that the percentage among women is the highest in West Virginia and lowest in Hawaii. Again, this percentage among men did not show a decrease as obvious as that among women, showing that in states where women are "happier" (indicated by fewer days mental health is not good in the past month), men are not more likely to be "happier" as well. This finding also suggests that the gender difference in this outcome is larger in some states than others. The last barplot, with the prevalence of self-reported >15 days mental health not good grouped by gender in each US state in descending order, shows that the ten states that have the largest difference of the estimated percent of self-reported >15 days mental health not good in the past 30 days are, in order, Oklahoma, West Virginia, Alabama, Wyoming, Indiana, Utah, Iowa, Wisconsin, Virginia, and Kentucky. Among these ten states, West Virginia, Alabama, Kentucky, and Utah are also among the top 10 states where the highest percent of women reported >15 days of mental health not good in the past 30 days. A table showing the top 10 states with the highest prevalence of self-reported past depression among women, self-reported >15 days mental health not good among women, and the largest difference in these two mental health outcomes by gender were presented below. 


### Regression Analysis
Logistic regressions were employed to analyze how the exposures (gender and the number of children in households) and demographic covariates (race, age, marital status), socioeconomic covariates (education, income, employment), and health-related covariates (general health and exercise) are associated with the outcome variables, self-reported past depression and self-reported number of days of bad mental health in the past 30 days. The regression models were first constructed for the outcome variables, self-reported past depression. Examining the relationship between the outcome variable and exposures (gender and the number of children in households) only, we found the fitted logistic regression model to be ŷ = 0.171 + 1.968*female + 0.931*children (none or two) + 0.893*children (three or more). Then, controlling for the demographic covariates (race, age, marital status), we had the fitted regression model on top of the exposures to be ŷ = 0.199 + 2.066*female + 0.871*children (none or two) + 0.846*children (three or more) + 0.534*race (Black) + 0.319*race (Asian) + 0.536*race (Hispanic) + 0.937*race (Other) + 0.971*age (30 to 49) + 0.809*age (50 to 64) + 0.474*age (65+) + 1.695*marital status (not married). Moreover, with both demographic covariates (race, age, marital status) and socioeconomic covariates (education, income, employment) being controlled, the resulting fitted regression model is ŷ = 0.262 + 2.036*female + 0.880*children (none or two) + 0.816*children (three or more) + 0.460*race (Black) + 0.344*race (Asian) + 0.450*race (Hispanic) + 0.816*race (Other) + 0.963*age (30 to 49) + 0.721*age (50 to 64) + 0.434*age (65+) + 1.318*marital status (not married) + 1.060*education (high school or some college) + 1.009*education (bachelors or higher) + 0.806*income (35,000 to 75,000) + 0.679*income (> 75,000) + 1.152*employment (homemaker/student/retired) + 2.531*employment (unemployed). Lastly, by controlling for all the covariates above and the health-related covariates (general health and exercise), we obtained the fitted logistic regression model as is ŷ = 0.107 + 2.066*female + 0.892*children (none or two) + 0.850*children (three or more) + 0.443*race (Black) + 0.342*race (Asian) + 0.430*race (Hispanic) + 0.787*race (Other) + 0.843*age (30 to 49) + 0.568*age (50 to 64) + 0.326*age (65+) + 1.307*marital status (not married) + 1.198*education (high school or some college) + 1.238*education (bachelors or higher) + 0.879*income (35,000 to 75,000) + 0.805*income (> 75,000) + 1.116*employment (homemaker/student/retired) + 2.051*employment (unemployed) + 2.205*general health (very good/good) + 5.303*general health (poor) + 1.141*exercise (no exercise). Since 4 different regression models were generated, AIC test was conducted to select the “best” fitted model. With AIC values being 396110.7, 370597.7, 280968.4, and 270506.8 for the model with exposures only, the model controlling for demographic covariates, the model controlling for demographic and socioeconomic covariates, and the model controlling for demographic covariates, socioeconomic covariates, and health-related covariates, respectively, we selected our final model to be the one with the smallest AIC value, which is the full model with all three types of covariates controlled, ŷ = 0.107 + 2.066*female + 0.892*children (none or two) + 0.850*children (three or more) + 0.443*race (Black) + 0.342*race (Asian) + 0.430*race (Hispanic) + 0.787*race (Other) + 0.843*age (30 to 49) + 0.568*age (50 to 64) + 0.326*age (65+) + 1.307*marital status (not married) + 1.198*education (high school or some college) + 1.238*education (bachelors or higher) + 0.879*income (35,000 to 75,000) + 0.805*income (> 75,000) + 1.116*employment (homemaker/student/retired) + 2.051*employment (unemployed) + 2.205*general health (very good/good) + 5.303*general health (poor) + 1.141*exercise (no exercise).

Additionally, we also examined the relationship between the number of children in the household and self-reported depression diagnosis among men and women. For male, we obtained the fitted regression model to be ŷ = 0.093 + 0.838*children (none or two) + 0.785*children (three or more) + 0.560*race (Black) + 0.381*race (Asian) + 0.513*race (Hispanic) + 0.966*race (Other) + 0.942*age (30 to 49) + 0.588*age (50 to 64) + 0.368*age (65+) + 1.359*marital status (not married) + 1.190*education (high school or some college) + 1.325*education (bachelors or higher) + 0.841*income (35,000 to 75,000) + 0.812*income (> 75,000) + 1.317*employment (homemaker/student/retired) + 2.364*employment (unemployed) + 2.046*general health (very good/good) + 4.783*general health (poor) + 1.217*exercise (no exercise). For female, we had the fitted regression model to be ŷ = 0.243 + 0.942*children (none or two) + 0.915*children (three or more) + 0.385*race (Black) + 0.319*race (Asian) + 0.382*race (Hispanic) + 0.674*race (Other) + 0.778*age (30 to 49) + 0.548*age (50 to 64) + 0.301*age (65+) + 1.290*marital status (not married) + 1.187*education (high school or some college) + 1.156*education (bachelors or higher) + 0.909*income (35,000 to 75,000) + 0.814*income (> 75,000) + 1.015*employment (homemaker/student/retired) + 1.827*employment (unemployed) + 2.324*general health (very good/good) + 5.708*general health (poor) + 1.101*exercise (no exercise). Accordingly, based on the regression models for men and women, it can be concluded that the number of children influences depression among women and men in different ways. 

The same logistic regression model constructions were repeated for the other outcome variable, number of days with bad mental health, with the same exposures (gender and the number of children in households), demographic covariates (race, age, marital status), socioeconomic covariates (education, income, employment), and health-related covariates (general health and exercise) to study the association between the covariates and the outcome. Examining the relationship between the number of days with bad mental health and exposures (gender and the number of children in households) only, we found the fitted logistic regression model to be ŷ = 0.092 + 1.498*female + 1.001*children (none or two) + 0.992*children (three or more). Then, controlling for the demographic covariates (race, age, marital status), we had the fitted regression model on top of the exposures to be ŷ = 0.091 + 1.568*female + 0.905*children (none or two) + 0.906*children (three or more) + 0.879*race (Black) + 0.527*race (Asian) + 0.711*race (Hispanic) + 1.273*race (Other) + 0.943*age (30 to 49) + 0.785*age (50 to 64) + 0.412*age (65+) + 1.882*marital status (not married). Moreover, with both demographic covariates (race, age, marital status) and socioeconomic covariates (education, income, employment) being controlled, the resulting fitted regression model is ŷ = 0.164 + 1.551*female + 0.870*children (none or two) + 0.856*children (three or more) + 0.755*race (Black) + 0.607*race (Asian) + 0.573*race (Hispanic) + 1.066*race (Other) + 0.905*age (30 to 49) + 0.629*age (50 to 64) + 0.374*age (65+) + 1.314*marital status (not married) + 0.990*education (high school or some college) + 0.730*education (bachelors or higher) + 0.721*income (35,000 to 75,000) + 0.579*income (> 75,000) + 1.000*employment (homemaker/student/retired) + 2.515*employment (unemployed). Lastly, by controlling for all the covariates above and the health-related covariates (general health and exercise), we obtained the fitted logistic regression model as is ŷ = 0.064 + 1.548*female + 0.893*children (none or two) + 0.906*children (three or more) + 0.740*race (Black) + 0.619*race (Asian) + 0.545*race (Hispanic) + 1.028*race (Other) + 0.744*age (30 to 49) + 0.436*age (50 to 64) + 0.345*age (65+) + 1.295*marital status (not married) + 1.179*education (high school or some college) + 0.975*education (bachelors or higher) + 0.812*income (35,000 to 75,000) + 0.737*income (> 75,000) + 0.956*employment (homemaker/student/retired) + 1.864*employment (unemployed) + 1.925*general health (very good/good) + 6.750*general health (poor) + 1.304*exercise (no exercise). Since 4 different regression models were generated, AIC test was conducted to select the “best” fitted model. With AIC values being 269586.8, 251648.9, 189028.7, and 178201.3 for the model with exposures only, the model controlling for demographic covariates, the model controlling for demographic and socioeconomic covariates, and the model controlling for demographic covariates, socioeconomic covariates, and health-related covariates, respectively, we selected our final model to be the one with the smallest AIC value, which is the full model with all three types of covariates controlled ŷ = 0.064 + 1.548*female + 0.893*children (none or two) + 0.906*children (three or more) + 0.740*race (Black) + 0.619*race (Asian) + 0.545*race (Hispanic) + 1.028*race (Other) + 0.744*age (30 to 49) + 0.436*age (50 to 64) + 0.345*age (65+) + 1.295*marital status (not married) + 1.179*education (high school or some college) + 0.975*education (bachelors or higher) + 0.812*income (35,000 to 75,000) + 0.737*income (> 75,000) + 0.956*employment (homemaker/student/retired) + 1.864*employment (unemployed) + 1.925*general health (very good/good) + 6.750*general health (poor) + 1.304*exercise (no exercise).
 
Additionally, we also examined the relationship between the number of children in the household and self-reported depression diagnosis among men and women. For male, we obtained the fitted regression model to be ŷ = 0.067 + 0.933*children (none or two) + 1.017*children (three or more) + 0.858*race (Black) + 0.506*race (Asian) + 0.600*race (Hispanic) + 0.986*race (Other) + 0.742*age (30 to 49) + 0.407*age (50 to 64) + 0.251*age (65+) + 1.321*marital status (not married) + 1.092*education (high school or some college) + 0.964*education (bachelors or higher) + 0.755*income (35,000 to 75,000) + 0.711*income (> 75,000) + 1.064*employment (homemaker/student/retired) + 2.114*employment (unemployed) + 1.744*general health (very good/good) + 6.387*general health (poor) + 1.362*exercise (no exercise). For female, we had the fitted regression model to be ŷ = 0.094 + 0.880*children (none or two) + 0.868*children (three or more) + 0.674*race (Black) + 0.693*race (Asian) + 0.509*race (Hispanic) + 1.055*race (Other) + 0.744*age (30 to 49) + 0.450*age (50 to 64) + 0.238*age (65+) + 1.295*marital status (not married) + 1.246*education (high school or some college) + 0.976*education (bachelors or higher) + 0.852*income (35,000 to 75,000) + 0.762*income (> 75,000) + 0.906*employment (homemaker/student/retired) + 1.704 *employment (unemployed) + 2.081*general health (very good/good) + 7.061*general health (poor) + 1.276*exercise (no exercise). Accordingly, based on the regression models for men and women, it can be concluded that the number of children influences the number of days with bad mental health among women and men in different ways. 



## Discussion
### Takeaways 

### Next steps

### Challenges

### Limitations

## Conclusion