---
title: "shiny_tests"
author: "Ziqing Wang"
date: "2022-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(survey)
```

```{r}
newdata_test1 <- data.frame(sex="female", 
                           children = "none",
                           race = "black",
                           age = "30-49",
                           marital_status = "married",
                           education = "bachelors or higher",
                           income = ">75000",
                           employment = "employed",
                           general_health = "fair/poor",
                           exercise = "no")

predict(full_mod_depr, newdata_test1, type = "response")


```


```{r}
full_mod_depr_rm =  svyglm(depression ~ sex + children + # exposures
           race + age + # demographic covariates
           education + income + employment + # socioeconomic covariates
           general_health + exercise, # health-related covariates
       brfss_design,
       family = quasibinomial())  
svypredmeans(full_mod_depr_rm, ~marital_status)


```

```{r}
svyglm(depression ~ sex,
       brfss_design,
       family = quasibinomial())  
```
```{r}
test_svy_obj = brfss_design %>% select(sex) 
test_svy_obj$variables
```

