---
title: "state-level mental health outcomes"
author: "Ziqing Wang"
date: "2022-11-22"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(survey)
library(srvyr)
library(readr)
library(forcats)
library(plotly)
```

## import data
```{r}
brfss21_data = read_csv("./data/cleaned_brfss21.csv") %>%
  mutate(mh_cat3 = factor(mh_cat3, levels = c("none", "<=15 days", ">15 days")),
         mh_bin = factor(mh_bin, levels = c("<=15 days", ">15 days")),
         depression = factor(depression, levels = c("no", "yes")),
         sex = factor(sex, levels = c("male", "female")),
         children = factor(children, levels = c("none", "one or two", "three or more")),
         state = factor(state),
         race = factor(race, levels = c("white", "black", "asian", "hispanic", "other")),
         education = factor(education, levels = c("less than high school", "high school or some college", "bachelors or higher")),
         income = factor(income, levels = c("<=35000", "35000-75000", ">75000")),
         employment = factor(employment, levels = c("employed", "homemaker/student/retired", "unemployed")),
         age = factor(age, levels = c("18-29", "30-49", "50-64", "65+")),
         general_health = factor(general_health, levels = c("excellent", "very good/good", "fair/poor")),
         exercise = factor(exercise, levels = c("yes", "no")))
head(brfss21_data)
```

Next, create a survey design object for incorporating sample weights.
```{r}
# Set options for allowing a single observation per stratum 
options(survey.lonely.psu = "adjust")

# Create survey design 
brfss_design = as_survey_design(brfss21_data, id = 1, strata = ststr, weight = llcpwt)

```

## State-level prevalence of depression by gender

Overall data frame
```{r}
depr_prev_bystate_gender = brfss_design %>%
  group_by(state_code, sex, depression) %>%
  summarize(depression_prev = 100*survey_mean(na.rm = T, vartype = c("ci")))

depr_prev_bystate_gender
```
Interactive map for women:
```{r}
depr_prev_bystate_f = depr_prev_bystate_gender %>%
  filter(sex == "female", depression == "yes")

depr_prev_bystate_f_graph = plot_geo(depr_prev_bystate_f, 
                                     locationmode = "USA-states",
                                     text = ~paste('95% CI: (', 
                                                   round(depression_prev_low,3),
                                                   round(depression_prev_upp,3),
                                                   ")")) %>%
  add_trace(locations = ~state_code,
            z = ~depression_prev,
            color = ~depression_prev,
            colors = "Purples") %>%
  layout(geo = list(scope = "usa"),
         #legend = list(title = list(text = "<b>Cylinders</b>")),
         title = "Prevalence of diagnosis of depression (%) among women") %>%
  colorbar(ticksuffix = "%") 


depr_prev_bystate_f_graph
```

Interactive map for men:
```{r}
depr_prev_bystate_m = depr_prev_bystate_gender %>%
  filter(sex == "male", depression == "yes")

depr_prev_bystate_m_graph = plot_geo(depr_prev_bystate_m, 
                                     locationmode = "USA-states",
                                     text = ~paste('95% CI: (', 
                                                   round(depression_prev_low,3),
                                                   round(depression_prev_upp,3),
                                                   ")")) %>%
  add_trace(locations = ~state_code,
            z = ~depression_prev,
            color = ~depression_prev,
            colors = "Purples") %>%
  layout(geo = list(scope = "usa"),
         #legend = list(title = list(text = "<b>Cylinders</b>")),
         title = "Prevalence of diagnosis of depression (%) among men") %>%
  colorbar(ticksuffix = "%") 


depr_prev_bystate_m_graph
```

Interactive map for gender difference in prevalence across states
```{r}
# construct new data frame for plotting
depr_prev_bystate_diff = depr_prev_bystate_gender %>%
  select(state_code, depression_prev, sex, depression) %>%
  filter(depression == "yes") %>%
  pivot_wider(names_from = "sex",
              values_from = "depression_prev") %>%
  mutate(difference = female - male)

# construct plot
depr_prev_bystate_diff_graph = plot_geo(depr_prev_bystate_diff, 
                                     locationmode = "USA-states",
                                     text = ~paste("Difference in prevalence: ",
                                                   round(difference,3))) %>%
  add_trace(locations = ~state_code,
            z = ~round(difference,3),
            color = ~difference,
            colors = "Purples") %>%
  layout(geo = list(scope = "usa"),
         #legend = list(title = list(text = "<b>Cylinders</b>")),
         title = "Difference in prevalence (%) of diagnosis of depression (F minus M)") %>%
  colorbar(ticksuffix = "%") 


depr_prev_bystate_diff_graph
```

